# Generated by Django 5.2.5 on 2025-08-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_repairlog_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='notepending',
            name='resolving_report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
