# Generated by Django 5.2.5 on 2025-08-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_notepending_resolving_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
